import { create } from "../bancos.js"

export async function createAle1(){
    let r
    r=15//================== RODADA 15 =====================//
    await create(r,'freuni',[4,6,20,45,-84])
    await create(r,'maiein',[40,-67])
    await create(r,'schbay',[-38,-52])
    await create(r,'hercol',[9,54])
    await create(r,'werlei',[-13,56,-70])
    await create(r,'levstu',[30,82])
    await create(r,'hofwol',[42,-45,-56])
    await create(r,'augboc',[-58])
    await create(r,'monbor',[4,-19,26,30,-40,46])
    r=14//================== RODADA 14 =====================//
    await create(r,'leifre',[54,56,-68,78])
    await create(r,'uniaug',[7,-8,22,-39])
    await create(r,'schmai',[10])
    await create(r,'einhof',[6,8,29,-37,-46,56])
    await create(r,'collev',[30,-65,-71])
    await create(r,'stuher',[3,-19,90])
    await create(r,'bocmon',[7,12,-62])
    await create(r,'baywer',[6,-10,22,26,28,82,84])
    await create(r,'wolbor',[6,90])
    r=13//================== RODADA 13 =====================//
    await create(r,'frecol',[53,64])
    await create(r,'levuni',[46,56,58,68,76])
    await create(r,'wersch',[30,76,-89])
    await create(r,'maiwol',[-33,-70,-84])
    await create(r,'hoflei',[-17,50,-57,-69])
    await create(r,'borboc',[8,12,45])
    await create(r,'augein',[1,-13,-64])
    await create(r,'herbay',[-12,-37,-38,40,45])
    await create(r,'monstu',[4,25,-35,90])
    r=12//================== RODADA 12 =====================//
    await create(r,'colhof',[13,-35])
    await create(r,'schfre',[-45,-61])
    await create(r,'unimon',[-33,79,90])
    await create(r,'einbor',[-20,26,-52])
    await create(r,'wolboc',[27,35,58,80])
    await create(r,'stuaug',[-4,15,90])
    await create(r,'baymai',[5,28,43,-45,57,79,-82,86])
    await create(r,'leilev',[32,83])
    await create(r,'werher',[85])
    r=11//================== RODADA 11 =====================//
    await create(r,'hersch',[49,-85,88])
    await create(r,'bocuni',[43,71,-90])
    await create(r,'monein',[-6,-29,-45,72])
    await create(r,'frewer',[56,80])
    await create(r,'borstu',[2,13,44,53,72])
    await create(r,'auglei',[34,51,64,-72,-89,-90])
    await create(r,'levwol',[17,-28,-54,76])
    await create(r,'hofbay',[-17,-38])
    await create(r,'maicol',[11,35,40,73,83])
    r=10//================== RODADA 10 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=9//================== RODADA 9 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=8//================== RODADA 8 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=7//================== RODADA 7 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=6//================== RODADA 6 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=5//================== RODADA 5 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=4//================== RODADA 4 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=3//================== RODADA 3 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=2//================== RODADA 2 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=1//================== RODADA 1 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
}