import { create } from "../bancos.js"

export async function create1(){
    let r
    r=15//================== RODADA 15 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=14//================== RODADA 14 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=13//================== RODADA 13 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=12//================== RODADA 12 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=11//================== RODADA 11 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=10//================== RODADA 10 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=9//================== RODADA 9 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=8//================== RODADA 8 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=7//================== RODADA 7 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=6//================== RODADA 6 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=5//================== RODADA 5 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=4//================== RODADA 4 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=3//================== RODADA 3 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=2//================== RODADA 2 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=1//================== RODADA 1 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
}