import { create } from "../bancos.js"

export async function createBra1novo(){
    let r
    r=15//================== RODADA 15 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=14//================== RODADA 14 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=13//================== RODADA 13 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=12//================== RODADA 12 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=11//================== RODADA 11 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=10//================== RODADA 10 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=9//================== RODADA 9 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=8//================== RODADA 8 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=7//================== RODADA 7 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=6//================== RODADA 6 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=5//================== RODADA 5 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=4//================== RODADA 4 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=3//================== RODADA 3 =====================//
    await create(r,'forflu',[29,35,-45,60,-69,79])
    await create(r,'ctbsao',[12,-81])
    await create(r,'palcor',[16,36,-76])
    await create(r,'sanamg',[-7,19,-49,69,90])
    await create(r,'bracru',[-1,-64,-87])
    await create(r,'amgapr',[10,84,-90])
    await create(r,'flabot',[-30,-45,58,-71,86])
    await create(r,'cuigre',[-10,29,-68])
    await create(r,'intgoi',[52])
    await create(r,'vasbah',[-44])
    r=2//================== RODADA 2 =====================//
    await create(r,'fluapr',[11,67])
    await create(r,'saoamg',[21,82,90])
    await create(r,'cuibra',[67,-86])
    await create(r,'crugre',[64])
    await create(r,'intfla',[-63,67,90])
    await create(r,'sanamg',[])
    await create(r,'vaspal',[29,40,-45,-62])
    await create(r,'ctbfor',[-51,-83,-90])
    await create(r,'goicor',[-17,31,80,90])
    await create(r,'bahbot',[-29,41,-78])
    r=1//================== RODADA 1 =====================//
    await create(r,'gresan',[44])
    await create(r,'flactb',[12,56,90])
    await create(r,'corcru',[68,87,-90])
    await create(r,'amgvas',[-5,-10,45])
    await create(r,'forint',[-54,56])
    await create(r,'aprgoi',[36,57])
    await create(r,'brabah',[-45,54,70])
    await create(r,'botsao',[4,-15,88])
    await create(r,'amgflu',[-52,-60,-72])
    await create(r,'palcui',[5,-45,65])
}