import { create } from "../bancos.js"

export async function createBra1novo(){
    let r
    r=15//================== RODADA 15 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=14//================== RODADA 14 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=13//================== RODADA 13 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=12//================== RODADA 12 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=11//================== RODADA 11 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=10//================== RODADA 10 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=9//================== RODADA 9 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=8//================== RODADA 8 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=7//================== RODADA 7 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=6//================== RODADA 6 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=5//================== RODADA 5 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=4//================== RODADA 4 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=3//================== RODADA 3 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=2//================== RODADA 2 =====================//
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    await create(r,'',[])
    r=1//================== RODADA 1 =====================//
    await create(r,'gresan',[44])
    await create(r,'flactb',[12,56,90])
    await create(r,'corcru',[68,87,-90])
    await create(r,'amgvas',[-5,-10,45])
    await create(r,'forint',[-54,56])
    await create(r,'aprgoi',[36,57])
    await create(r,'brabah',[-45,54,70])
    await create(r,'botsao',[4,-15,88])
    await create(r,'amgflu',[-52,-60,-72])
    await create(r,'palcui',[5,-45,65])
}