import { create } from "../bancos.js"

export async function create1(){
    let r
    
    r=30//================== RODADA 30 =====================//
    await create(r,'','2310')
    await create(r,'','2310')
    await create(r,'','2310')
    await create(r,'','2310')
    await create(r,'','2310')
    await create(r,'','2310')
    await create(r,'','2310')
    await create(r,'','2310')
    await create(r,'','2310')
    await create(r,'','2310')
    r=29//================== RODADA 29 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=28//================== RODADA 28 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=27//================== RODADA 27 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=26//================== RODADA 26 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=25//================== RODADA 26 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=24//================== RODADA 24 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=23//================== RODADA 23 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=22//================== RODADA 22 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=21//================== RODADA 21 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=20//================== RODADA 20 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=19//================== RODADA 19 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=18//================== RODADA 18 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=17//================== RODADA 17 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=16//================== RODADA 16 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=15//================== RODADA 15 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=14//================== RODADA 14 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=13//================== RODADA 13 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=12//================== RODADA 12 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=11//================== RODADA 11 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=10//================== RODADA 10 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=9//================== RODADA 9 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=8//================== RODADA 8 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=7//================== RODADA 7 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=6//================== RODADA 6 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=5//================== RODADA 5 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=4//================== RODADA 4 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=3//================== RODADA 3 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=2//================== RODADA 2 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=1//================== RODADA 1 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
}