import { create } from "../bancos.js"

export async function createIng1(){
    let r
    
    r=7//================== RODADA 7 =====================//
    await create(r,'astbri','2309300830')
    await create(r,'maucry','2309301100')
    await create(r,'newbur','2309301100')
    await create(r,'wolmac','2309301100')
    await create(r,'bouars','2309301100')
    await create(r,'wesshe','2309301100')
    await create(r,'evelut','2309301100')
    await create(r,'totliv','2309301330')
    await create(r,'notbre','2310011000')
    await create(r,'fulche','2310021600')
    r=6//================== RODADA 6 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=5//================== RODADA 5 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=4//================== RODADA 4 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=3//================== RODADA 3 =====================//
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    await create(r,'',[],[])
    r=2//================== RODADA 2 =====================//
    await create(r,'notshe',[6,7],[3,-48,89])
    await create(r,'livbou',[10,2],[-3,28,36,62])
    await create(r,'wolbri',[5,3],[-15,-46,-51,-55,61])
    await create(r,'fulbre',[5,5],[-44,-66,-90])
    await create(r,'totmau',[5,6],[49,83])
    await create(r,'macnew',[3,0],[31])
    await create(r,'asteve',[7,6],[18,24,51,75])
    await create(r,'wesche',[3,9],[7,-28,53,90])
    await create(r,'cryars',[1,8],[-54])
    await create(r,'',[],[])
    r=1//================== RODADA 1 =====================//
    await create(r,'burmac',[6,5],[-4,-36,-75])
    await create(r,'arsnot',[8,3],[26,32,-82])
    await create(r,'shecry',[5,5],[-49])
    await create(r,'bouwes',[10,4],[-51,82])
    await create(r,'brilut',[6,7],[36,71,-81,85,90])
    await create(r,'eveful',[10,4],[-73])
    await create(r,'newast',[6,5],[6,-11,16,58,77,90])
    await create(r,'bretot',[3,6],[-11,27,36,-45])
    await create(r,'cheliv',[4,4],[-18,37])
    await create(r,'mauwol',[8,7],[76])
}